### ISSUE TITLE
OpenEPaperLink-PyStation Help needed

### ISSUE THREAD

**Issue by nikkisstuff** [jjwbruijn/OpenEPaperLink#215]
I have flashed my cc2531 with the correct firmware and the tag displays AP Found. I have put my png image in the OpenEPaperLink-PyStation  folder and renamed it with the mac address but it will not upload. What am i missing? It returns 

2024-02-01 20:46:53,155 - logic - INFO - Checkin from MAC 78:01:05:56:1c:85:c6:00
2024-02-01 20:46:53,156 - logic - INFO - No image found for 78:01:05:56:1c:85:c6:00
2024-02-01 20:47:33,369 - logic - DEBUG - <AvailableDataRequest: outerChecksum=23, sourceMac=00c6851c56050178, innerChecksum=110, lastPacketLQI=54, lastPacketRSSI=-81, temperature=0, batteryMv=24588, hwType=0, wakeupReason=0>

**Comment by nikkisstuff** [comment]
Thanks For your help i will defiantly look at your fork.

I added the cache folder but when it try's to upload i get the following error. I am using a hanshow nebular tag.

```
C:\Users\nikki\Desktop\Project folders\openEpaperlink\OpenEPaperLink-master\OpenEPaperLink-master\ARM_Tag_FW\cc2531_OEPL\OpenEPaperLink-PyStation>main.py
2024-02-02 21:36:50,951 - logic - DEBUG - <AvailableDataRequest: outerChecksum=55, sourceMac=00c6851c56050178, innerChecksum=126, lastPacketLQI=63, lastPacketRSSI=-81, temperature=0, batteryMv=24588, hwType=0, wakeupReason=0>
2024-02-02 21:36:50,951 - logic - INFO - Checkin from MAC 78:01:05:56:1c:85:c6:00
Traceback (most recent call last):
  File "C:\Users\nikki\Desktop\Project folders\openEpaperlink\OpenEPaperLink-master\OpenEPaperLink-master\ARM_Tag_FW\cc2531_OEPL\OpenEPaperLink-PyStation\main.py", line 274, in <module>
    Logic().main_loop()
  File "C:\Users\nikki\Desktop\Project folders\openEpaperlink\OpenEPaperLink-master\OpenEPaperLink-master\ARM_Tag_FW\cc2531_OEPL\OpenEPaperLink-PyStation\main.py", line 106, in main_loop
    self.parseUart(b[0])
  File "C:\Users\nikki\Desktop\Project folders\openEpaperlink\OpenEPaperLink-master\OpenEPaperLink-master\ARM_Tag_FW\cc2531_OEPL\OpenEPaperLink-PyStation\main.py", line 81, in parseUart
    self.handle_adr(data_request);
  File "C:\Users\nikki\Desktop\Project folders\openEpaperlink\OpenEPaperLink-master\OpenEPaperLink-master\ARM_Tag_FW\cc2531_OEPL\OpenEPaperLink-PyStation\main.py", line 143, in handle_adr
    data = self.pic.get_image(mac + ".png", data_type)
  File "C:\Users\nikki\Desktop\Project folders\openEpaperlink\OpenEPaperLink-master\OpenEPaperLink-master\ARM_Tag_FW\cc2531_OEPL\OpenEPaperLink-PyStation\pic_fs.py", line 35, in get_image
    data = self.load_image(image_path, data_type)
  File "C:\Users\nikki\Desktop\Project folders\openEpaperlink\OpenEPaperLink-master\OpenEPaperLink-master\ARM_Tag_FW\cc2531_OEPL\OpenEPaperLink-PyStation\pic_fs.py", line 81, in load_image
    is_similar = abs(pixel[0] - c[0]) < 128 \
TypeError: 'int' object is not subscriptable 
```

**Comment by nikkisstuff** [comment]
I have found the problem The image i resized was not the correct format
